namespace Template {
    export async function scn_brokenglass(): ƒS.SceneReturn {
        ƒS.Speech.hide();
        await ƒS.update(1);
        await ƒS.Sound.fade(sound.Dumm, 0, 1, true);
        await ƒS.Sound.fade(sound.Street, 1, 2, true);
        await ƒS.Location.show(backgrounds.BG_Autovermietung);
        await ƒS.update(1);
        await ƒS.Character.show(characters.Alice, characters.Alice.pose.default, ƒS.positions.bottomcenter);
        await ƒS.update(0.5);
        await ƒS.Speech.tell(characters.Alice, "Hier sind wir.");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Hier war doch bis vor kurzem noch eine Autovermietung.");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.narrator, "Ja, ich erinnere mich dunkel... Das hier muss meine Autovermietung gewesen sein...");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Da hat sich wohl jemand ganz schön bedient.");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.narrator, "Sieht so aus. Vielleicht hat dieser Einbruch etwas mit meinem Gedächtnisverlust zu tun.");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Haben Sie dir das nicht alles im Krankenhaus gesagt?");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.narrator, "Nein...");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Kommt mir sehr verdächtig vor...");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Hier standen früher so viele Autos, kaum zu glauben, dass das alles dir gehört hat.");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Aber..");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Ich habe ein ungutes Gefühl hier. Ich habe das Gefühl als würde man uns beobachten.");
        await ƒS.update(0.4);
        await ƒS.Speech.tell(characters.Alice, "Lass uns zu mir gehen, hier bist du doch eh nicht sicher.");
        await ƒS.update(0.4);
        await ƒS.Sound.fade(sound.Street, 0, 1, true);
        await ƒS.Speech.tell(characters.narrator, "Okay...");
        await ƒS.update(0.4);
        ƒS.Character.hideAll();
        ƒS.Speech.hide();
        await ƒS.update(0.4);
        await ƒS.Location.show(backgrounds.BG_Black);
        await ƒS.update(0.4);
        await ƒS.Location.show(backgrounds.BG_Stunde);
        await ƒS.update(0.4);
        await ƒS.update(2);
        await ƒS.Location.show(backgrounds.BG_Black);
        await ƒS.update(0.4);
        await ƒS.Location.show(backgrounds.BG_BeiAlice);
        await ƒS.update(0.4);
        return scn_beiAlice();
    };
}